Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,7 +38,12 @@ jobs:
       
       - name: Download deploy script from S3
         run: |
-          aws s3 cp s3://autodeploy-scripts/working2/* ./ --recursive
+          set -e
+          echo "Downloading deploy scripts..."
+          if ! aws s3 cp s3://autodeploy-scripts/working2/* ./ --recursive; then
+          echo "No files found or S3 access failed. Exiting..."
+          exit 1
+          fi
 
       - name: Make deploy script executable
         run: chmod +x ./deploy_lambda.sh
